[project]
name = "underwater-visual-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-contrib-python>=4.12.0.88",
    "opencv-python>=4.12.0.88",
    "pyyaml>=6.0.3",
    "ultralytics>=8.3.228",
]
